-- AlterTable
ALTER TABLE `admin_logs` MODIFY `action` ENUM('ROLE_CHANGE', 'STATUS_CHANGE', 'SUBSCRIPTION_CHANGE', 'SUBSCRIPTION_CANCEL', 'SUBSCRIPTION_OVERRIDE', 'FREEMIUM_CONFIG_CHANGE', 'PLAN_CHANGE') NOT NULL;
